version: 2
jobs:
  test-and-build:
    environment:
      - _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
    docker:
      - image: cimg/clojure:1.11.1-openjdk-8.0-node
    steps:
      - checkout

      # core
      # - run:
      #     name: test frontend clj
      #     command: cd frontend && clojure -X:test
      - run:
          name: test frontend cljs
          command: clojure -X:test-cljs
      - run:
          name: Build frontend
          command: clojure -T:build jar
      - save-cache:
          paths:
            - ~/bin
            - ~/.m2
          key: frontend-{{ checksum "build.clj" }}
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  deploy:
    docker:
      - image: cimg/clojure:1.11.1-openjdk-8.0-node
    steps:
      - checkout
      - restore_cache:
          key: frontend-{{ checksum "build.clj" }}
      - attach_workspace:
          at: ./
      - run:
          name: Deploy frontend to clojars
          command: clojure -T:build deploy
workflows:
  version: 2
  build:
    jobs:
      - test-and-build
      - deploy:
          filters:
            branches:
              only:
                - release
          requires:
            - test-and-build
